<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lesson Modules for Teaching Visual Analytics</title>
  <meta name="description" content="Lessons on teaching visual analytics in a generic undergraduate classroom">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Lesson Modules for Teaching Visual Analytics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lessons on teaching visual analytics in a generic undergraduate classroom" />
  <meta name="github-repo" content="BawCOS/teaching-visual-analytics" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lesson Modules for Teaching Visual Analytics" />
  
  <meta name="twitter:description" content="Lessons on teaching visual analytics in a generic undergraduate classroom" />
  

<meta name="author" content="David Ebert">
<meta name="author" content="Bradley Warner">


<meta name="date" content="2018-06-25">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="Intro2.html">
<link rel="next" href="Viz2.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet" />
<script src="libs/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<script src="libs/jquery-ui-1.11.4/jquery.ui.touch-punch.min.js"></script>
<link href="libs/c3-0.4.11/c3.min.css" rel="stylesheet" />
<script src="libs/c3-0.4.11/c3.min.js"></script>
<script src="libs/d3-3.5.9/d3.min.js"></script>
<link href="libs/pivottable-2.11.0/pivot.min.css" rel="stylesheet" />
<script src="libs/pivottable-2.11.0/pivot.min.js"></script>
<script src="libs/pivottable_d3renderers-2.11.0/d3_renderers.min.js"></script>
<script src="libs/pivottable_c3renderers-2.11.0/c3_renderers.min.js"></script>
<script src="libs/polyfill-0.1/polyfill.min.js"></script>
<link href="libs/rpivotTable_style-0.1/rpivotTable.css" rel="stylesheet" />
<script src="libs/rpivotTable-binding-0.2.0/rpivotTable.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.2/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.2/js/bootstrap.min.js"></script>
<link href="libs/d3scatter-0.0.0/d3scatter.css" rel="stylesheet" />
<script src="libs/d3scatter-0.0.0/d3scatter.js"></script>
<script src="libs/d3scatter-binding-0.1.0/d3scatter.js"></script>
<link href="libs/ionrangeslider-2.1.2/css/ion.rangeSlider.css" rel="stylesheet" />
<link href="libs/ionrangeslider-2.1.2/css/ion.rangeSlider.skinShiny.css" rel="stylesheet" />
<script src="libs/ionrangeslider-2.1.2/js/ion.rangeSlider.min.js"></script>
<script src="libs/strftime-0.9.2/strftime-min.js"></script>
<link href="libs/selectize-0.11.2/css/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.11.2/js/selectize.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Lesson Notes for Visual Analytics</a></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="who-is-this-book-for.html"><a href="who-is-this-book-for.html"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="book-structure-and-how-to-use-it.html"><a href="book-structure-and-how-to-use-it.html"><i class="fa fa-check"></i><b>0.2</b> Book Structure and How to Use It</a><ul>
<li class="chapter" data-level="0.2.1" data-path="book-structure-and-how-to-use-it.html"><a href="book-structure-and-how-to-use-it.html#introduction"><i class="fa fa-check"></i><b>0.2.1</b> Introduction</a></li>
<li class="chapter" data-level="0.2.2" data-path="book-structure-and-how-to-use-it.html"><a href="book-structure-and-how-to-use-it.html#intent"><i class="fa fa-check"></i><b>0.2.2</b> Intent</a></li>
<li class="chapter" data-level="0.2.3" data-path="book-structure-and-how-to-use-it.html"><a href="book-structure-and-how-to-use-it.html#use"><i class="fa fa-check"></i><b>0.2.3</b> Use</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="prerequisites.html"><a href="prerequisites.html"><i class="fa fa-check"></i><b>0.3</b> Prerequisites</a></li>
<li class="chapter" data-level="0.4" data-path="software-packages.html"><a href="software-packages.html"><i class="fa fa-check"></i><b>0.4</b> Software Packages</a></li>
<li class="chapter" data-level="0.5" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i><b>0.5</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="Chpt1.html"><a href="Chpt1.html"><i class="fa fa-check"></i><b>1</b> Introducing Visual Analytics - Emphasis on Analytic Reasoning</a><ul>
<li class="chapter" data-level="1.1" data-path="lesson-preparation.html"><a href="lesson-preparation.html"><i class="fa fa-check"></i><b>1.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="1.1.1" data-path="lesson-preparation.html"><a href="lesson-preparation.html#objectives"><i class="fa fa-check"></i><b>1.1.1</b> Objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="lesson-preparation.html"><a href="lesson-preparation.html#preparation"><i class="fa fa-check"></i><b>1.1.2</b> Preparation</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="Intro1.html"><a href="Intro1.html"><i class="fa fa-check"></i><b>1.2</b> Lesson Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="AR1.html"><a href="AR1.html"><i class="fa fa-check"></i><b>1.3</b> Analytic Reasoning</a><ul>
<li class="chapter" data-level="1.3.1" data-path="AR1.html"><a href="AR1.html#analytic-reasoning-explained"><i class="fa fa-check"></i><b>1.3.1</b> Analytic Reasoning Explained</a></li>
<li class="chapter" data-level="1.3.2" data-path="AR1.html"><a href="AR1.html#example"><i class="fa fa-check"></i><b>1.3.2</b> Example</a></li>
<li class="chapter" data-level="1.3.3" data-path="AR1.html"><a href="AR1.html#second-example"><i class="fa fa-check"></i><b>1.3.3</b> Second Example</a></li>
<li class="chapter" data-level="1.3.4" data-path="AR1.html"><a href="AR1.html#other-problem-ideas"><i class="fa fa-check"></i><b>1.3.4</b> Other problem ideas:</a></li>
<li class="chapter" data-level="1.3.5" data-path="AR1.html"><a href="AR1.html#using-analytic-reasoning."><i class="fa fa-check"></i><b>1.3.5</b> Using Analytic Reasoning.</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="Viz1.html"><a href="Viz1.html"><i class="fa fa-check"></i><b>1.4</b> Visualizing data (Re-representation)</a><ul>
<li class="chapter" data-level="1.4.1" data-path="Viz1.html"><a href="Viz1.html#background-on-visualizing-data"><i class="fa fa-check"></i><b>1.4.1</b> Background on Visualizing Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="Viz1.html"><a href="Viz1.html#using-problem"><i class="fa fa-check"></i><b>1.4.2</b> Using Problem</a></li>
<li class="chapter" data-level="1.4.3" data-path="Viz1.html"><a href="Viz1.html#discussion-ideas-4"><i class="fa fa-check"></i><b>1.4.3</b> Discussion ideas</a></li>
<li class="chapter" data-level="1.4.4" data-path="Viz1.html"><a href="Viz1.html#visualization"><i class="fa fa-check"></i><b>1.4.4</b> Visualization</a></li>
<li class="chapter" data-level="1.4.5" data-path="Viz1.html"><a href="Viz1.html#vectors-for-visualization"><i class="fa fa-check"></i><b>1.4.5</b> Vectors for Visualization</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="Inert1.html"><a href="Inert1.html"><i class="fa fa-check"></i><b>1.5</b> Interaction</a><ul>
<li class="chapter" data-level="1.5.1" data-path="Inert1.html"><a href="Inert1.html#background-information-on-interaction"><i class="fa fa-check"></i><b>1.5.1</b> Background Information on Interaction</a></li>
<li class="chapter" data-level="1.5.2" data-path="Inert1.html"><a href="Inert1.html#our-problem"><i class="fa fa-check"></i><b>1.5.2</b> Our Problem</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="final-product.html"><a href="final-product.html"><i class="fa fa-check"></i><b>1.6</b> Final Product</a><ul>
<li class="chapter" data-level="1.6.1" data-path="final-product.html"><a href="final-product.html#discussion-ideas-12"><i class="fa fa-check"></i><b>1.6.1</b> Discussion Ideas</a></li>
<li class="chapter" data-level="1.6.2" data-path="final-product.html"><a href="final-product.html#first-knowledge-product"><i class="fa fa-check"></i><b>1.6.2</b> First Knowledge Product</a></li>
<li class="chapter" data-level="1.6.3" data-path="final-product.html"><a href="final-product.html#discussion-ideas-13"><i class="fa fa-check"></i><b>1.6.3</b> Discussion Ideas</a></li>
<li class="chapter" data-level="1.6.4" data-path="final-product.html"><a href="final-product.html#second-knowledge-product"><i class="fa fa-check"></i><b>1.6.4</b> Second Knowledge Product</a></li>
<li class="chapter" data-level="1.6.5" data-path="final-product.html"><a href="final-product.html#web-resources"><i class="fa fa-check"></i><b>1.6.5</b> Web Resources</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="Conc1.html"><a href="Conc1.html"><i class="fa fa-check"></i><b>1.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Chpt2.html"><a href="Chpt2.html"><i class="fa fa-check"></i><b>2</b> Exploratory Visual Analytics</a><ul>
<li class="chapter" data-level="2.1" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html"><i class="fa fa-check"></i><b>2.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="2.1.1" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html#objectives-1"><i class="fa fa-check"></i><b>2.1.1</b> Objectives:</a></li>
<li class="chapter" data-level="2.1.2" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html#preparation-1"><i class="fa fa-check"></i><b>2.1.2</b> Preparation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="Intro2.html"><a href="Intro2.html"><i class="fa fa-check"></i><b>2.2</b> Lesson Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="DataCol2.html"><a href="DataCol2.html"><i class="fa fa-check"></i><b>2.3</b> Data Collection</a><ul>
<li class="chapter" data-level="2.3.1" data-path="DataCol2.html"><a href="DataCol2.html#load-packages"><i class="fa fa-check"></i><b>2.3.1</b> Load Packages</a></li>
<li class="chapter" data-level="2.3.2" data-path="DataCol2.html"><a href="DataCol2.html#Pop2"><i class="fa fa-check"></i><b>2.3.2</b> Population</a></li>
<li class="chapter" data-level="2.3.3" data-path="DataCol2.html"><a href="DataCol2.html#population-density"><i class="fa fa-check"></i><b>2.3.3</b> Population Density</a></li>
<li class="chapter" data-level="2.3.4" data-path="DataCol2.html"><a href="DataCol2.html#life-expectancy"><i class="fa fa-check"></i><b>2.3.4</b> Life Expectancy</a></li>
<li class="chapter" data-level="2.3.5" data-path="DataCol2.html"><a href="DataCol2.html#fertility-rates"><i class="fa fa-check"></i><b>2.3.5</b> Fertility Rates</a></li>
<li class="chapter" data-level="2.3.6" data-path="DataCol2.html"><a href="DataCol2.html#child-mortality"><i class="fa fa-check"></i><b>2.3.6</b> Child Mortality</a></li>
<li class="chapter" data-level="2.3.7" data-path="DataCol2.html"><a href="DataCol2.html#aging-population"><i class="fa fa-check"></i><b>2.3.7</b> Aging Population</a></li>
<li class="chapter" data-level="2.3.8" data-path="DataCol2.html"><a href="DataCol2.html#final-data"><i class="fa fa-check"></i><b>2.3.8</b> Final Data</a></li>
<li class="chapter" data-level="2.3.9" data-path="DataCol2.html"><a href="DataCol2.html#economic-data"><i class="fa fa-check"></i><b>2.3.9</b> Economic Data</a></li>
<li class="chapter" data-level="2.3.10" data-path="DataCol2.html"><a href="DataCol2.html#summary-of-data-collection"><i class="fa fa-check"></i><b>2.3.10</b> Summary of Data Collection</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="Viz2.html"><a href="Viz2.html"><i class="fa fa-check"></i><b>2.4</b> Visualization of Data</a><ul>
<li class="chapter" data-level="2.4.1" data-path="Viz2.html"><a href="Viz2.html#first-visualizations"><i class="fa fa-check"></i><b>2.4.1</b> First Visualizations</a></li>
<li class="chapter" data-level="2.4.2" data-path="Viz2.html"><a href="Viz2.html#next-visualizations---adding-years-and-focussing"><i class="fa fa-check"></i><b>2.4.2</b> Next Visualizations - Adding Years and Focussing</a></li>
<li class="chapter" data-level="2.4.3" data-path="Viz2.html"><a href="Viz2.html#conclusion-from-visualization"><i class="fa fa-check"></i><b>2.4.3</b> Conclusion from Visualization</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html"><i class="fa fa-check"></i><b>2.5</b> Interactions with Visualizations</a><ul>
<li class="chapter" data-level="2.5.1" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html#first-interactive-plots"><i class="fa fa-check"></i><b>2.5.1</b> First Interactive Plots</a></li>
<li class="chapter" data-level="2.5.2" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html#nest-gapminder-data-by-country"><i class="fa fa-check"></i><b>2.5.2</b> nest gapminder data by country</a></li>
<li class="chapter" data-level="2.5.3" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html#add-in-a-plot-column-with-map_plot"><i class="fa fa-check"></i><b>2.5.3</b> add in a plot column with map_plot</a></li>
<li class="chapter" data-level="2.5.4" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html#plot-it"><i class="fa fa-check"></i><b>2.5.4</b> plot it</a></li>
<li class="chapter" data-level="2.5.5" data-path="interactions-with-visualizations.html"><a href="interactions-with-visualizations.html#dt-options-httpsrstudio.github.iodtoptions.html"><i class="fa fa-check"></i><b>2.5.5</b> DT options <a href="https://rstudio.github.io/DT/options.html" class="uri">https://rstudio.github.io/DT/options.html</a></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Chpt3.html"><a href="Chpt3.html"><i class="fa fa-check"></i><b>3</b> Inference in Visual Analytics</a><ul>
<li class="chapter" data-level="3.1" data-path="lesson-preparation-differences.html"><a href="lesson-preparation-differences.html"><i class="fa fa-check"></i><b>3.1</b> Lesson Preparation Differences</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="Chpt4.html"><a href="Chpt4.html"><i class="fa fa-check"></i><b>4</b> Forecasting and Prediction</a><ul>
<li class="chapter" data-level="4.1" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html"><i class="fa fa-check"></i><b>4.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="4.1.1" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html#objectives-2"><i class="fa fa-check"></i><b>4.1.1</b> Objectives:</a></li>
<li class="chapter" data-level="4.1.2" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html#preparation-2"><i class="fa fa-check"></i><b>4.1.2</b> Preparation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="case-study.html"><a href="case-study.html"><i class="fa fa-check"></i><b>5</b> Case Study</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="AppA.html"><a href="AppA.html"><i class="fa fa-check"></i><b>A</b> Lesson Handouts</a></li>
<li class="chapter" data-level="B" data-path="AppB.html"><a href="AppB.html"><i class="fa fa-check"></i><b>B</b> Project</a><ul>
<li class="chapter" data-level="B.0.1" data-path="AppB.html"><a href="AppB.html#introduction-1"><i class="fa fa-check"></i><b>B.0.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bawcos.github.io/teaching-visual-analytics/" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lesson Modules for Teaching Visual Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="DataCol2" class="section level2">
<h2><span class="header-section-number">2.3</span> Data Collection</h2>
<p>The data for this lesson comes from the <a href="https://www.gapminder.org/data/">Gapminder</a> website. Again, you could just start with the <strong>tools</strong> application on the website instead of using the <code>R</code> code here. This section will be long but remember that data wrangling can take up to 80% of the time in a project. We also provide the final data in a csv file on the github site for this book. The file name is Gapminder_final.csv.</p>
<div id="load-packages" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Load Packages</h3>
<p>First we will load the packages we need for this chapter. The list below are the packages we will be using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readxl)
<span class="kw">library</span>(gapminder)
<span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(GGally)
<span class="kw">library</span>(plotly)
<span class="kw">library</span>(crosstalk)
<span class="kw">library</span>(ggthemes)
<span class="kw">library</span>(geofacet)
<span class="kw">library</span>(DT)
<span class="kw">library</span>(d3scatter)
<span class="kw">library</span>(rbokeh)
<span class="kw">library</span>(trelliscopejs)</code></pre></div>
<p>First data is downloaded in a Excel spreadsheet from the <a href="https://www.gapminder.org/data/">Gapminder</a> website. We will use the package <strong>readxl</strong> to read it into <code>R</code>. In addition, <code>R</code> has a package called <strong>gapminder</strong> which is a subset of the data from the Gapminder website. We will use it to get country names to reduce the size of our data and exclude countries with a large amount of missing data.</p>
<p>If you want to skip the data collection and cleaning steps, data has been downloaded and is in the <strong>data</strong> folder on the GitHub site for this book.</p>
</div>
<div id="Pop2" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Population</h3>
<p>The first data set we will be working with is the population for each country.</p>
<div id="import-data" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> Import Data</h4>
<p>First import the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator gapminder population.xlsx&quot;</span>)</code></pre></div>
<p>Look at the first few rows of the data to get a feel for the data.</p>
<table>
<thead>
<tr class="header">
<th align="left">Total population</th>
<th align="right">1800.0</th>
<th align="right">1810.0</th>
<th align="right">1820.0</th>
<th align="right">1830.0</th>
<th align="right">1840.0</th>
<th align="right">1850.0</th>
<th align="right">1860.0</th>
<th align="right">1870.0</th>
<th align="right">1880.0</th>
<th align="right">1890.0</th>
<th align="right">1900.0</th>
<th align="right">1910.0</th>
<th align="right">1920.0</th>
<th align="right">1930.0</th>
<th align="right">1940.0</th>
<th align="right">1950.0</th>
<th align="right">1951.0</th>
<th align="right">1952.0</th>
<th align="right">1953.0</th>
<th align="right">1954.0</th>
<th align="right">1955.0</th>
<th align="right">1956.0</th>
<th align="right">1957.0</th>
<th align="right">1958.0</th>
<th align="right">1959.0</th>
<th align="right">1960.0</th>
<th align="right">1961.0</th>
<th align="right">1962.0</th>
<th align="right">1963.0</th>
<th align="right">1964.0</th>
<th align="right">1965.0</th>
<th align="right">1966.0</th>
<th align="right">1967.0</th>
<th align="right">1968.0</th>
<th align="right">1969.0</th>
<th align="right">1970.0</th>
<th align="right">1971.0</th>
<th align="right">1972.0</th>
<th align="right">1973.0</th>
<th align="right">1974.0</th>
<th align="right">1975.0</th>
<th align="right">1976.0</th>
<th align="right">1977.0</th>
<th align="right">1978.0</th>
<th align="right">1979.0</th>
<th align="right">1980.0</th>
<th align="right">1981.0</th>
<th align="right">1982.0</th>
<th align="right">1983.0</th>
<th align="right">1984.0</th>
<th align="right">1985.0</th>
<th align="right">1986.0</th>
<th align="right">1987.0</th>
<th align="right">1988.0</th>
<th align="right">1989.0</th>
<th align="right">1990.0</th>
<th align="right">1991.0</th>
<th align="right">1992.0</th>
<th align="right">1993.0</th>
<th align="right">1994.0</th>
<th align="right">1995.0</th>
<th align="right">1996.0</th>
<th align="right">1997.0</th>
<th align="right">1998.0</th>
<th align="right">1999.0</th>
<th align="right">2000.0</th>
<th align="right">2001.0</th>
<th align="right">2002.0</th>
<th align="right">2003.0</th>
<th align="right">2004.0</th>
<th align="right">2005.0</th>
<th align="right">2006.0</th>
<th align="right">2007.0</th>
<th align="right">2008.0</th>
<th align="right">2009.0</th>
<th align="right">2010.0</th>
<th align="right">2011.0</th>
<th align="right">2012.0</th>
<th align="right">2013.0</th>
<th align="right">2014.0</th>
<th align="right">2015.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Abkhazia</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="right">3280000</td>
<td align="right">3280000</td>
<td align="right">3323519</td>
<td align="right">3448982</td>
<td align="right">3625022</td>
<td align="right">3810047</td>
<td align="right">3973968</td>
<td align="right">4169690</td>
<td align="right">4419695</td>
<td align="right">4710171</td>
<td align="right">5021241</td>
<td align="right">5351413</td>
<td align="right">5813814</td>
<td align="right">6394908</td>
<td align="right">7034081</td>
<td align="right">7752118</td>
<td align="right">7839426</td>
<td align="right">7934798</td>
<td align="right">8038312</td>
<td align="right">8150037</td>
<td align="right">8270024</td>
<td align="right">8398309</td>
<td align="right">8534913</td>
<td align="right">8679848</td>
<td align="right">8833127</td>
<td align="right">8994793</td>
<td align="right">9164945</td>
<td align="right">9343772</td>
<td align="right">9531555</td>
<td align="right">9728645</td>
<td align="right">9935358</td>
<td align="right">10148841</td>
<td align="right">10368600</td>
<td align="right">10599790</td>
<td align="right">10849510</td>
<td align="right">11121097</td>
<td align="right">11412821</td>
<td align="right">11716896</td>
<td align="right">12022514</td>
<td align="right">12315553</td>
<td align="right">12582954</td>
<td align="right">12831361</td>
<td align="right">13056499</td>
<td align="right">13222547</td>
<td align="right">13283279</td>
<td align="right">13211412</td>
<td align="right">12996923</td>
<td align="right">12667001</td>
<td align="right">12279095</td>
<td align="right">11912510</td>
<td align="right">11630498</td>
<td align="right">11438949</td>
<td align="right">11337932</td>
<td align="right">11375768</td>
<td align="right">11608351</td>
<td align="right">12067570</td>
<td align="right">12789374</td>
<td align="right">13745630</td>
<td align="right">14824371</td>
<td align="right">15869967</td>
<td align="right">16772522</td>
<td align="right">17481800</td>
<td align="right">18034130</td>
<td align="right">18511480</td>
<td align="right">19038420</td>
<td align="right">19701940</td>
<td align="right">20531160</td>
<td align="right">21487079</td>
<td align="right">22507368</td>
<td align="right">23499850</td>
<td align="right">24399948</td>
<td align="right">25183615</td>
<td align="right">25877544</td>
<td align="right">26528741</td>
<td align="right">27207291</td>
<td align="right">27962207</td>
<td align="right">28809167</td>
<td align="right">29726803</td>
<td align="right">30682500</td>
<td align="right">31627506</td>
<td align="right">32526562</td>
</tr>
<tr class="odd">
<td align="left">Akrotiri and Dhekelia</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">10661</td>
<td align="right">10737</td>
<td align="right">10813</td>
<td align="right">10889</td>
<td align="right">10966</td>
<td align="right">11043</td>
<td align="right">11121</td>
<td align="right">11200</td>
<td align="right">11279</td>
<td align="right">11358</td>
<td align="right">11439</td>
<td align="right">11519</td>
<td align="right">11601</td>
<td align="right">11683</td>
<td align="right">11765</td>
<td align="right">11848</td>
<td align="right">11932</td>
<td align="right">12016</td>
<td align="right">12101</td>
<td align="right">12187</td>
<td align="right">12273</td>
<td align="right">12359</td>
<td align="right">12447</td>
<td align="right">12535</td>
<td align="right">12623</td>
<td align="right">12712</td>
<td align="right">12802</td>
<td align="right">12892</td>
<td align="right">12983</td>
<td align="right">13075</td>
<td align="right">13167</td>
<td align="right">13260</td>
<td align="right">13354</td>
<td align="right">13448</td>
<td align="right">13543</td>
<td align="right">13639</td>
<td align="right">13735</td>
<td align="right">13832</td>
<td align="right">13930</td>
<td align="right">14028</td>
<td align="right">14127</td>
<td align="right">14227</td>
<td align="right">14328</td>
<td align="right">14429</td>
<td align="right">14531</td>
<td align="right">14633</td>
<td align="right">14737</td>
<td align="right">14841</td>
<td align="right">14946</td>
<td align="right">15051</td>
<td align="right">15157</td>
<td align="right">15264</td>
<td align="right">15372</td>
<td align="right">15481</td>
<td align="right">15590</td>
<td align="right">15700</td>
<td align="right">15700</td>
<td align="right">15700</td>
<td align="right">15700</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="right">410445</td>
<td align="right">423591</td>
<td align="right">438671</td>
<td align="right">457234</td>
<td align="right">478227</td>
<td align="right">506889</td>
<td align="right">552800</td>
<td align="right">610036</td>
<td align="right">672544</td>
<td align="right">741688</td>
<td align="right">819950</td>
<td align="right">901122</td>
<td align="right">963956</td>
<td align="right">1015991</td>
<td align="right">1123210</td>
<td align="right">1263171</td>
<td align="right">1287499</td>
<td align="right">1316086</td>
<td align="right">1348097</td>
<td align="right">1382881</td>
<td align="right">1419969</td>
<td align="right">1459089</td>
<td align="right">1500152</td>
<td align="right">1543224</td>
<td align="right">1588478</td>
<td align="right">1636054</td>
<td align="right">1685901</td>
<td align="right">1737645</td>
<td align="right">1790533</td>
<td align="right">1843596</td>
<td align="right">1896125</td>
<td align="right">1947786</td>
<td align="right">1998695</td>
<td align="right">2049147</td>
<td align="right">2099657</td>
<td align="right">2150602</td>
<td align="right">2202040</td>
<td align="right">2253842</td>
<td align="right">2305999</td>
<td align="right">2358467</td>
<td align="right">2411229</td>
<td align="right">2464338</td>
<td align="right">2517869</td>
<td align="right">2571845</td>
<td align="right">2626290</td>
<td align="right">2681245</td>
<td align="right">2735329</td>
<td align="right">2788315</td>
<td align="right">2842620</td>
<td align="right">2901590</td>
<td align="right">2966799</td>
<td align="right">3041003</td>
<td align="right">3121336</td>
<td align="right">3197064</td>
<td align="right">3253659</td>
<td align="right">3281453</td>
<td align="right">3275438</td>
<td align="right">3240613</td>
<td align="right">3189623</td>
<td align="right">3140634</td>
<td align="right">3106727</td>
<td align="right">3092034</td>
<td align="right">3092471</td>
<td align="right">3102898</td>
<td align="right">3114851</td>
<td align="right">3121965</td>
<td align="right">3124093</td>
<td align="right">3123112</td>
<td align="right">3117045</td>
<td align="right">3103758</td>
<td align="right">3082172</td>
<td align="right">3050741</td>
<td align="right">3010849</td>
<td align="right">2968026</td>
<td align="right">2929886</td>
<td align="right">2901883</td>
<td align="right">2886010</td>
<td align="right">2880667</td>
<td align="right">2883281</td>
<td align="right">2889676</td>
<td align="right">2896679</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="right">2503218</td>
<td align="right">2595056</td>
<td align="right">2713079</td>
<td align="right">2880355</td>
<td align="right">3082721</td>
<td align="right">3299305</td>
<td align="right">3536468</td>
<td align="right">3811028</td>
<td align="right">4143163</td>
<td align="right">4525691</td>
<td align="right">4946166</td>
<td align="right">5404045</td>
<td align="right">6063800</td>
<td align="right">6876190</td>
<td align="right">7797418</td>
<td align="right">8872247</td>
<td align="right">9039913</td>
<td align="right">9216395</td>
<td align="right">9405445</td>
<td align="right">9609507</td>
<td align="right">9829717</td>
<td align="right">10065829</td>
<td align="right">10316288</td>
<td align="right">10578453</td>
<td align="right">10848971</td>
<td align="right">11124892</td>
<td align="right">11404859</td>
<td align="right">11690152</td>
<td align="right">11985130</td>
<td align="right">12295973</td>
<td align="right">12626953</td>
<td align="right">12980269</td>
<td align="right">13354197</td>
<td align="right">13744383</td>
<td align="right">14144437</td>
<td align="right">14550033</td>
<td align="right">14960111</td>
<td align="right">15377095</td>
<td align="right">15804428</td>
<td align="right">16247113</td>
<td align="right">16709098</td>
<td align="right">17190236</td>
<td align="right">17690184</td>
<td align="right">18212331</td>
<td align="right">18760761</td>
<td align="right">19337723</td>
<td align="right">19943667</td>
<td align="right">20575701</td>
<td align="right">21228288</td>
<td align="right">21893857</td>
<td align="right">22565908</td>
<td align="right">23241276</td>
<td align="right">23917889</td>
<td align="right">24591493</td>
<td align="right">25257671</td>
<td align="right">25912364</td>
<td align="right">26554277</td>
<td align="right">27180921</td>
<td align="right">27785977</td>
<td align="right">28362015</td>
<td align="right">28904300</td>
<td align="right">29411839</td>
<td align="right">29887717</td>
<td align="right">30336880</td>
<td align="right">30766551</td>
<td align="right">31183658</td>
<td align="right">31590320</td>
<td align="right">31990387</td>
<td align="right">32394886</td>
<td align="right">32817225</td>
<td align="right">33267887</td>
<td align="right">33749328</td>
<td align="right">34261971</td>
<td align="right">34811059</td>
<td align="right">35401790</td>
<td align="right">36036159</td>
<td align="right">36717132</td>
<td align="right">37439427</td>
<td align="right">38186135</td>
<td align="right">38934334</td>
<td align="right">39666519</td>
</tr>
<tr class="even">
<td align="left">American Samoa</td>
<td align="right">8170</td>
<td align="right">8156</td>
<td align="right">8142</td>
<td align="right">8128</td>
<td align="right">8114</td>
<td align="right">7958</td>
<td align="right">7564</td>
<td align="right">7057</td>
<td align="right">6582</td>
<td align="right">6139</td>
<td align="right">5949</td>
<td align="right">7047</td>
<td align="right">8173</td>
<td align="right">10081</td>
<td align="right">13135</td>
<td align="right">18937</td>
<td align="right">19295</td>
<td align="right">19543</td>
<td align="right">19683</td>
<td align="right">19729</td>
<td align="right">19706</td>
<td align="right">19647</td>
<td align="right">19597</td>
<td align="right">19606</td>
<td align="right">19729</td>
<td align="right">20012</td>
<td align="right">20478</td>
<td align="right">21118</td>
<td align="right">21883</td>
<td align="right">22701</td>
<td align="right">23518</td>
<td align="right">24320</td>
<td align="right">25116</td>
<td align="right">25886</td>
<td align="right">26615</td>
<td align="right">27292</td>
<td align="right">27916</td>
<td align="right">28490</td>
<td align="right">29014</td>
<td align="right">29491</td>
<td align="right">29932</td>
<td align="right">30325</td>
<td align="right">30690</td>
<td align="right">31105</td>
<td align="right">31670</td>
<td align="right">32456</td>
<td align="right">33488</td>
<td align="right">34740</td>
<td align="right">36165</td>
<td align="right">37687</td>
<td align="right">39247</td>
<td align="right">40835</td>
<td align="right">42448</td>
<td align="right">44049</td>
<td align="right">45591</td>
<td align="right">47044</td>
<td align="right">48379</td>
<td align="right">49597</td>
<td align="right">50725</td>
<td align="right">51807</td>
<td align="right">52874</td>
<td align="right">53926</td>
<td align="right">54942</td>
<td align="right">55899</td>
<td align="right">56768</td>
<td align="right">57522</td>
<td align="right">58176</td>
<td align="right">58729</td>
<td align="right">59117</td>
<td align="right">59262</td>
<td align="right">59117</td>
<td align="right">58648</td>
<td align="right">57904</td>
<td align="right">57031</td>
<td align="right">56226</td>
<td align="right">55636</td>
<td align="right">55316</td>
<td align="right">55227</td>
<td align="right">55302</td>
<td align="right">55434</td>
<td align="right">55538</td>
</tr>
</tbody>
</table>
<p>From the <strong>gapminder</strong> package, obtain the subset of countries where the data is most complete.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries&lt;-<span class="kw">levels</span>(gapminder<span class="op">$</span>country)</code></pre></div>
<p>Finally, wrangle the data into the final form needed. The term used is tidy data; each row is an observation and each column a variable. As currently imported, the data is in a wide format where the value of years, which is a single variable, are used as column titles. Switch to a long format.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,pop,<span class="op">-</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year),<span class="dt">pop=</span><span class="kw">as.integer</span>(pop)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)</code></pre></div>
<p>Table <a href="DataCol2.html#tab:tab-pop">2.1</a> is the first 6 rows of our data.</p>
<table>
<caption><span id="tab:tab-pop">Table 2.1: </span>Population Data Arranged into Rows</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="right">year</th>
<th align="right">pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="right">1950</td>
<td align="right">7752118</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="right">1950</td>
<td align="right">1263171</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="right">1950</td>
<td align="right">8872247</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="right">1950</td>
<td align="right">4354882</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="right">1950</td>
<td align="right">17150335</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="right">1950</td>
<td align="right">8177344</td>
</tr>
</tbody>
</table>
</div>
<div id="quality-check" class="section level4">
<h4><span class="header-section-number">2.3.2.2</span> Quality Check</h4>
<p>Before proceeding, check the condition of the data and clean up any obvious issues. First compare the number of countries in our data with those in the <strong>gapminder</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(countries)</code></pre></div>
<pre><code>## [1] 142</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))</code></pre></div>
<pre><code>## [1] 139</code></pre>
<p>There are 142 countries in the <strong>gapminder</strong> data but only 139 in the data we collected that match those 142 countries. There might some names in <strong>gapminder</strong> that are different from the imported data. Check this idea first.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries[<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Korea, Dem. Rep.&quot; &quot;Korea, Rep.&quot;      &quot;Yemen, Rep.&quot;</code></pre>
<p>We are missing the two Koreas and Yemen from our data.</p>
<p>We need the full list of countries in the original data to change the names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,pop,<span class="op">-</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year),<span class="dt">pop=</span><span class="kw">as.integer</span>(pop)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Korea&quot;</span>,<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;North Korea&quot;           &quot;South Korea&quot;           &quot;United Korea (former)&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;North Yemen (former)&quot; &quot;South Yemen (former)&quot; &quot;Yemen&quot;</code></pre>
<p>We now know the problem is that in the <strong>gapminder</strong> package we have the titles:</p>
<p>“Korea, Dem. Rep.”<br />
“Korea, Rep.”<br />
“Yemen, Rep.”</p>
<p>while in our data from the gapminder website we have the names:</p>
<p>“North Korea”<br />
“South Korea”<br />
“Yemen”</p>
<p>Correct the names in the our data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;North Korea&quot;</span>,<span class="st">&quot;Korea, Dem. Rep.&quot;</span>,gapminder_population<span class="op">$</span>country)
gapminder_population<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;South Korea&quot;</span>,<span class="st">&quot;Korea, Rep.&quot;</span>,gapminder_population<span class="op">$</span>country)
gapminder_population<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="st">&quot;Yemen, Rep.&quot;</span>,gapminder_population<span class="op">$</span>country)</code></pre></div>
<p>Now check our data again.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Finally get rid of the countries not in the <strong>gapminder</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries)</code></pre></div>
<p>Next look for missing observations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),]</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   country  year   pop
##   &lt;chr&gt;   &lt;int&gt; &lt;int&gt;
## 1 Taiwan   2014    NA
## 2 Taiwan   2015    NA</code></pre>
<p>We are missing the last two years of data for Taiwan. We could drop Taiwan or get another estimate of the population from the web. Using the website <a href="http://www.worldometers.info/world-population/taiwan-population/" class="uri">http://www.worldometers.info/world-population/taiwan-population/</a> we see that for the last four years the population has grown by about 70000 each year. We will estimate the population for 2014 and 2015 by adding 70000 to the population in 2013 for each year..</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),][<span class="dv">1</span>,<span class="dv">3</span>]=<span class="dv">23151000</span> <span class="op">+</span><span class="st"> </span><span class="dv">70000</span>
gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),][<span class="dv">1</span>,<span class="dv">3</span>]=<span class="dv">23151000</span> <span class="op">+</span><span class="st"> </span><span class="dv">140000</span></code></pre></div>
</div>
<div id="getting-data-into-final-form" class="section level4">
<h4><span class="header-section-number">2.3.2.3</span> Getting Data into Final Form</h4>
<p>Now add the continents names to the data frame. First get the country names and associated continent names from the <strong>gapminder</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dict&lt;-gapminder <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(continent) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="kw">as.character</span>(country))</code></pre></div>
<p>Add the continent names using a <code>join</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population &lt;-<span class="st"> </span>gapminder_population <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,pop)</code></pre></div>
<p>Table <a href="DataCol2.html#tab:tab-final-pop">2.2</a> shows the form of the final data set.</p>
<table>
<caption><span id="tab:tab-final-pop">Table 2.2: </span>Final Population Data</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">7752118</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">1263171</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">8872247</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">4354882</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">17150335</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">8177344</td>
</tr>
</tbody>
</table>
<p>To conclude, clean up the workspace by removing temporary objects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(gapminder_population_temp)</code></pre></div>
</div>
<div id="discussion-ideas-14" class="section level4">
<h4><span class="header-section-number">2.3.2.4</span> Discussion Ideas</h4>
<p>Even though the video we watched used population, what are the disadvantages of using raw population?</p>
<p>A large country will have a larger population because of size, what is another population metric that places the data on an equal scale?</p>
</div>
</div>
<div id="population-density" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Population Density</h3>
<p>Adjusting population by the size of the country gives a better basis to compare countries. The gapminder website has a data set on population density, the population divided by the area of the country in squared kilometers, but it only goes to the year 2010. The gapminder website also has a data file with the area of each country. It also only goes up to 2010. To find population density, we will import the surface area file and divide population by the surface area. This file only goes up to 2010 so we will have to assume that the area does not change in the last five years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/surface land.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area &lt;-<span class="st"> </span>gapminder_area <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,area,<span class="op">-</span><span class="st">&quot;Surface area (sq. km)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Surface area (sq. km)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">1960</span>,year<span class="op">&lt;</span><span class="dv">2011</span>)</code></pre></div>
<p>Next check the country names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries[<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Central African Republic&quot; &quot;Czech Republic&quot;          
## [3] &quot;Dominican Republic&quot;       &quot;Reunion&quot;                 
## [5] &quot;Taiwan&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Czech&quot;</span>,<span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Czech Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Dominican&quot;</span>,<span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Dominican Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Central&quot;</span>,<span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Central African Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Reunion&quot;</span>,<span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## character(0)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_area<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Taiwan&quot;</span>,<span class="kw">unique</span>(gapminder_area<span class="op">$</span>country))]</code></pre></div>
<pre><code>## character(0)</code></pre>
<p>We are missing Taiwan and Reunion from the data and for the other three mismatches we have Republic named as Rep.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Czech Rep.&quot;</span>,<span class="st">&quot;Czech Republic&quot;</span>,gapminder_area<span class="op">$</span>country)
gapminder_area<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Central African Rep.&quot;</span>,<span class="st">&quot;Central African Republic&quot;</span>,gapminder_area<span class="op">$</span>country)
gapminder_area<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Dominican Rep.&quot;</span>,<span class="st">&quot;Dominican Republic&quot;</span>,gapminder_area<span class="op">$</span>country)</code></pre></div>
<p>We will have to add Taiwan and Reunion after we complete the data consolidation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area&lt;-gapminder_area <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">is.na</span>(area)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(country) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unique</span>()</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   country
##   &lt;chr&gt;  
## 1 Belgium</code></pre>
<p>Belgium is missing data, so we will just fill just fill in the values with the value of 30530.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Belgium&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(area))</code></pre></div>
<pre><code>## # A tibble: 11 x 3
##    country  year  area
##    &lt;chr&gt;   &lt;int&gt; &lt;dbl&gt;
##  1 Belgium  2000 30530
##  2 Belgium  2001 30530
##  3 Belgium  2002 30530
##  4 Belgium  2003 30530
##  5 Belgium  2004 30530
##  6 Belgium  2005 30530
##  7 Belgium  2006 30530
##  8 Belgium  2007 30530
##  9 Belgium  2008 30530
## 10 Belgium  2009 30530
## 11 Belgium  2010 30530</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_area &lt;-<span class="st"> </span>gapminder_area <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">area=</span><span class="dv">30530</span>))</code></pre></div>
<p>Now merge the data with the population data and fill in the missing values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity &lt;-<span class="st"> </span>gapminder_population <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(gapminder_area,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;country&quot;</span>,<span class="st">&quot;year&quot;</span>))</code></pre></div>
<p>Fill in data for Taiwan and Reunion. Taiwan is missing its density. The area of Taiwan is <a href="https://www.statista.com/statistics/321367/taiwan-land-area/">36,000 squared kilometers</a> and the area of Reunion is 2510, .</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity[gapminder_popdensity<span class="op">$</span>country<span class="op">==</span><span class="st">&quot;Reunion&quot;</span>,<span class="st">&quot;area&quot;</span>] =<span class="st"> </span><span class="dv">2510</span>
gapminder_popdensity[gapminder_popdensity<span class="op">$</span>country<span class="op">==</span><span class="st">&quot;Taiwan&quot;</span>,<span class="st">&quot;area&quot;</span>] =<span class="st"> </span><span class="dv">36000</span></code></pre></div>
<p>Fill in the years prior to 1961 with the values from 1961.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity&lt;-<span class="st"> </span>gapminder_popdensity <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(country) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">fill</span>(area,<span class="dt">.direction=</span><span class="st">&quot;up&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(year,country)</code></pre></div>
<p>Fill in the missing value in the tail with the most recent values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity&lt;-<span class="st"> </span>gapminder_popdensity <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(country) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">fill</span>(area,<span class="dt">.direction=</span><span class="st">&quot;down&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(year,country)</code></pre></div>
<p>Calculate density by dividing population by area.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity &lt;-<span class="st"> </span>gapminder_popdensity <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">density=</span>pop<span class="op">/</span>area) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>area)</code></pre></div>
<p>Clean up the work space.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(gapminder_area)
<span class="kw">rm</span>(gapminder_population)</code></pre></div>
</div>
<div id="life-expectancy" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Life Expectancy</h3>
<p>Next bring in life expectancy data. Since the data source is the same as population we will have the same issue with the names of the Koreas and Yemen. We will be performing the same steps as section <a href="DataCol2.html#Pop2">2.3.2</a>, so the narrative on many of the steps is skipped.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator life_expectancy_at_birth.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp&lt;-gapminder_lifeexp_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,life_exp,<span class="op">-</span><span class="st">&quot;Life expectancy&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Life expectancy&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_lifeexp_temp)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;North Korea&quot;</span>,<span class="st">&quot;Korea, Dem. Rep.&quot;</span>,gapminder_lifeexp<span class="op">$</span>country)
gapminder_lifeexp<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;South Korea&quot;</span>,<span class="st">&quot;Korea, Rep.&quot;</span>,gapminder_lifeexp<span class="op">$</span>country)
gapminder_lifeexp<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="st">&quot;Yemen, Rep.&quot;</span>,gapminder_lifeexp<span class="op">$</span>country)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp&lt;-gapminder_lifeexp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_lifeexp))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp &lt;-<span class="st"> </span>gapminder_lifeexp <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,life_exp)</code></pre></div>
<p>Again <a href="DataCol2.html#tab:tab-lifeexp">2.3</a> shows the final data set.</p>
<table>
<caption><span id="tab:tab-lifeexp">Table 2.3: </span>Final Life Expectancy Data</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">life_exp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">26.85</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">54.48</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">42.77</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">30.70</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">61.61</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">69.01</td>
</tr>
</tbody>
</table>
</div>
<div id="fertility-rates" class="section level3">
<h3><span class="header-section-number">2.3.5</span> Fertility Rates</h3>
<p>Next fertility rates of a country may be an indication of its developmental state. Get the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator undata total_fertility.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility&lt;-gapminder_fertility_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,fertility,<span class="op">-</span><span class="st">&quot;Total fertility rate&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total fertility rate&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_fertility_temp)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;North Korea&quot;</span>,<span class="st">&quot;Korea, Dem. Rep.&quot;</span>,gapminder_fertility<span class="op">$</span>country)
gapminder_fertility<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;South Korea&quot;</span>,<span class="st">&quot;Korea, Rep.&quot;</span>,gapminder_fertility<span class="op">$</span>country)
gapminder_fertility<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="st">&quot;Yemen, Rep.&quot;</span>,gapminder_fertility<span class="op">$</span>country)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility&lt;-gapminder_fertility <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">unique</span>(gapminder_fertility<span class="op">$</span>country))</code></pre></div>
<pre><code>## [1] 142</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_fertility<span class="op">$</span>fertility))</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility[<span class="kw">is.na</span>(gapminder_fertility<span class="op">$</span>fertility),]</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   country  year fertility
##   &lt;chr&gt;   &lt;int&gt;     &lt;dbl&gt;
## 1 Taiwan   2014        NA
## 2 Taiwan   2015        NA</code></pre>
<p>Taiwan again has missing values. Estimate the fertility with average of the previous 5 years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp&lt;-<span class="kw">as.double</span>(gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Taiwan&quot;</span>,year<span class="op">&lt;</span><span class="dv">2014</span> <span class="op">&amp;</span><span class="st"> </span>year<span class="op">&gt;</span><span class="dv">2008</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">summarise</span>(<span class="dt">ave=</span><span class="kw">mean</span>(fertility)))
gapminder_fertility&lt;-gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">fertility=</span>temp))
<span class="kw">rm</span>(temp)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility &lt;-<span class="st"> </span>gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,fertility)</code></pre></div>
<p>Table <a href="DataCol2.html#tab:tab-fertility">2.4</a> is the final form of the fertility data.</p>
<table>
<caption><span id="tab:tab-fertility">Table 2.4: </span>Final Fertility Data</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">fertility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">7.67</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">5.80</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">7.65</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">6.93</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">3.16</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">3.07</td>
</tr>
</tbody>
</table>
</div>
<div id="child-mortality" class="section level3">
<h3><span class="header-section-number">2.3.6</span> Child Mortality</h3>
<p>Next collect data on child mortality. This data is the number of children out of 1000 born in the given year that will die before reaching the age of 5.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator gapminder under5mortality.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5&lt;-gapminder_mortality5_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,mortality,<span class="op">-</span><span class="st">&quot;Under five mortality&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Under five mortality&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_mortality5_temp)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;North Korea&quot;</span>,<span class="st">&quot;Korea, Dem. Rep.&quot;</span>,gapminder_mortality5<span class="op">$</span>country)
gapminder_mortality5<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;South Korea&quot;</span>,<span class="st">&quot;Korea, Rep.&quot;</span>,gapminder_mortality5<span class="op">$</span>country)
gapminder_mortality5<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="st">&quot;Yemen, Rep.&quot;</span>,gapminder_mortality5<span class="op">$</span>country)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5&lt;-gapminder_mortality5 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_mortality5<span class="op">$</span>mortality))</code></pre></div>
<pre><code>## [1] 156</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5[<span class="kw">is.na</span>(gapminder_mortality5<span class="op">$</span>mortality),]</code></pre></div>
<pre><code>## # A tibble: 156 x 3
##    country           year mortality
##    &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt;
##  1 Hong Kong, China  1950        NA
##  2 Puerto Rico       1950        NA
##  3 Reunion           1950        NA
##  4 Taiwan            1950        NA
##  5 Hong Kong, China  1951        NA
##  6 Puerto Rico       1951        NA
##  7 Reunion           1951        NA
##  8 Taiwan            1951        NA
##  9 Hong Kong, China  1952        NA
## 10 Puerto Rico       1952        NA
## # ... with 146 more rows</code></pre>
<p>Now Hong Kong, Puerto Rico, and Reunion are missing data up through the year 1979 and Taiwan is missing all years. We could drop Taiwan from the data but at this point that is a waste of information from the other data sets. We could impute the values but we need to be careful when we interpret the resulting plots. The first three countries mentioned are going to pose problems for the years prior to 1980. For ease will will drop these countries from the analysis after we get our final data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_mortality5 &lt;-<span class="st"> </span>gapminder_mortality5 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,mortality)</code></pre></div>
<p>The final data for child mortality is in Table <a href="DataCol2.html#tab:tab-mortality">2.5</a></p>
<table>
<caption><span id="tab:tab-mortality">Table 2.5: </span>Final Child Mortality Data</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">mortality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">439.56</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">165.17</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">292.13</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">404.92</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">93.53</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">31.60</td>
</tr>
</tbody>
</table>
</div>
<div id="aging-population" class="section level3">
<h3><span class="header-section-number">2.3.7</span> Aging Population</h3>
<p>Another idea is that developed countries have an older population by percentage. Collect data on the percent of population above 60 years in age.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator_total above 60 percen.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60&lt;-gapminder_above60_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,above_<span class="dv">60</span>,<span class="op">-</span><span class="st">&quot;Total above 60 (%)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total above 60 (%)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_above60_temp)</code></pre></div>
<p>This data came from a different source, so be careful about the country names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries[<span class="op">!</span>countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country)]</code></pre></div>
<pre><code>## [1] &quot;Central African Republic&quot; &quot;Czech Republic&quot;          
## [3] &quot;Dominican Republic&quot;       &quot;Taiwan&quot;</code></pre>
<p>Taiwan is still a problem but now there are three other countries that are in the <strong>gapminder</strong> package and not in the new data set. This is a problem with naming similar to what we found when finding density. Correct those first three countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Czech&quot;</span>,<span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Czech Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Dominican&quot;</span>,<span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Dominican Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Central&quot;</span>,<span class="kw">unique</span>(gapminder_above60<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Central African Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Czech Rep.&quot;</span>,<span class="st">&quot;Czech Republic&quot;</span>,gapminder_above60<span class="op">$</span>country)
gapminder_above60<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Central African Rep.&quot;</span>,<span class="st">&quot;Central African Republic&quot;</span>,gapminder_above60<span class="op">$</span>country)
gapminder_above60<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(<span class="st">&quot;Dominican Rep.&quot;</span>,<span class="st">&quot;Dominican Republic&quot;</span>,gapminder_above60<span class="op">$</span>country)</code></pre></div>
<p>Remove Taiwan since we have no data on it. While at it, remove Hong Kong, Puerto Rico, and Reunion. We could drop all data prior to 1980 but this is 30 years of data. Instead, we chose to drop these four small countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">final_countries&lt;-<span class="st"> </span>countries[<span class="op">!</span>countries <span class="op">%in%</span><span class="st"> </span>
<span class="kw">unique</span>(gapminder_mortality5[<span class="kw">is.na</span>(gapminder_mortality5<span class="op">$</span>mortality),]<span class="op">$</span>country)]</code></pre></div>
<p>Remove the four countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60&lt;-gapminder_above60 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>final_countries)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_above60<span class="op">$</span>above_<span class="dv">60</span>))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>There are no missing values.</p>
<p>The data is only for every 5 years and has projections past 2015. We will remove the projections and then interpolate for the remaining years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>year)</code></pre></div>
<pre><code>##  [1] 1950 1955 1960 1965 1970 1975 1980 1985 1990 1995 2000 2005 2010 2015
## [15] 2020 2025 2030 2035 2040 2045 2050</code></pre>
<p>First remove the projections.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60 &lt;-<span class="st"> </span>gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2015</span>)</code></pre></div>
<p>Before interpolating, plot two countries to get an idea of the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p&lt;-gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span> <span class="op">|</span><span class="st"> </span>country<span class="op">==</span><span class="st">&quot;United States&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>year,<span class="dt">y=</span>above_<span class="dv">60</span>,<span class="dt">color=</span>country))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() 
p</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
<p>We will be using a spline to interpolate, but first plot a linear interpolation to compare with the spline.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp1&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="kw">approx</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;Albania&quot;</span>)
temp2&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="kw">approx</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;United States&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp1,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp2,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Year&quot;</span>,<span class="dt">y=</span><span class="st">&quot;Percentage of Population above 60 years&quot;</span>,<span class="dt">title=</span><span class="st">&quot;Estimating Percent of Population Above 60&quot;</span>,<span class="dt">subtitle=</span><span class="st">&quot;Linear Interpolation&quot;</span>)</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>Now use a spline. This process fits a cubic spline between each point and will be smoother than the linear interpolation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp1&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="kw">spline</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;Albania&quot;</span>)
temp2&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="kw">spline</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;United States&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp1,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp2,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Year&quot;</span>,<span class="dt">y=</span><span class="st">&quot;Percentage of Population above 60 years&quot;</span>,<span class="dt">title=</span><span class="st">&quot;Estimating Percent of Population Above 60&quot;</span>,<span class="dt">subtitle=</span><span class="st">&quot;Spline Interpolation&quot;</span>)</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<p>Clean the work space.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(temp1)
<span class="kw">rm</span>(temp2)</code></pre></div>
<p>To aviod the temporary variables, use the code below in one step.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p<span class="op">+</span><span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="kw">spline</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;Albania&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="kw">spline</span>(year,above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;United States&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Year&quot;</span>,<span class="dt">y=</span><span class="st">&quot;Percentage of Population above 60 years&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Estimating Percent of Population Above 60&quot;</span>,<span class="dt">subtitle=</span><span class="st">&quot;Spline Interpolation&quot;</span>)</code></pre></div>
<p>Interpolate for every country and create our final data frame. Use the map function from the <strong>purrr</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60&lt;-gapminder_above60 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">split</span>(.<span class="op">$</span>country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">map</span>(<span class="op">~</span><span class="kw">data.frame</span>(<span class="kw">spline</span>(.<span class="op">$</span>year,.<span class="op">$</span>above_<span class="dv">60</span>,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">map2_df</span>(final_countries,<span class="op">~</span><span class="kw">update_list</span>(.x,<span class="dt">country=</span>.y)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(x),<span class="dt">above_60=</span>y) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,year,above_<span class="dv">60</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.tibble</span>()</code></pre></div>
<p>Finish by adding the continents.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60 &lt;-<span class="st"> </span>gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,above_<span class="dv">60</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(year,country)</code></pre></div>
<p>The first few rows of the final data frame:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>() <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">above_60</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">4.503620</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">10.131796</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">6.808316</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">4.944525</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">7.043321</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">12.458937</td>
</tr>
</tbody>
</table>
<p>Finally, clean up the figure by removing the background shading.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>gapminder_above60<span class="op">%&gt;%</span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>year,<span class="dt">y=</span>above_<span class="dv">60</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>gapminder_above60<span class="op">%&gt;%</span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>year,<span class="dt">y=</span>above_<span class="dv">60</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Year&quot;</span>,<span class="dt">y=</span><span class="st">&quot;Percentage of Population above 60 years&quot;</span>,<span class="dt">title=</span><span class="st">&quot;Estimating Percent of Population Above 60&quot;</span>,<span class="dt">subtitle=</span><span class="st">&quot;Spline Interpolation&quot;</span>) <span class="op">+</span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
</div>
<div id="final-data" class="section level3">
<h3><span class="header-section-number">2.3.8</span> Final Data</h3>
<p>First do a quick quality check.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_popdensity<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_lifeexp<span class="op">$</span>continent)<span class="op">/</span><span class="dv">67</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_fertility<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_mortality5<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_above60<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       51       24       31       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(dict<span class="op">$</span>continent)</code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<p>We have two problems left, the percentage of the population above 60 has less countries than the other data sets and life expectancy has one more year, 2016, than the other data sets. Resolve these problems by dropping the 4 countries and the year 2016.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_popdensity <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">Total=</span><span class="kw">n_distinct</span>(country))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   Total
##   &lt;int&gt;
## 1   142</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">Total=</span><span class="kw">n_distinct</span>(country))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   Total
##   &lt;int&gt;
## 1   138</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_popdensity<span class="op">$</span>country)[<span class="op">!</span><span class="kw">unique</span>(gapminder_popdensity<span class="op">$</span>country) <span class="op">%in%</span><span class="st"> </span>final_countries]</code></pre></div>
<pre><code>## [1] &quot;Hong Kong, China&quot; &quot;Puerto Rico&quot;      &quot;Reunion&quot;         
## [4] &quot;Taiwan&quot;</code></pre>
<p>Drop the countries by using the join function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_va &lt;-gapminder_above60 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(gapminder_lifeexp,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;country&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;continent&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(gapminder_fertility,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;country&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;continent&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(gapminder_popdensity,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;country&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;continent&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(gapminder_mortality5,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;country&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;continent&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(year,country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="kw">factor</span>(country),<span class="dt">pop=</span><span class="kw">round</span>(pop<span class="op">/</span><span class="dv">100000</span>,<span class="dv">2</span>),
         <span class="dt">above_60=</span><span class="kw">round</span>(above_<span class="dv">60</span>,<span class="dv">2</span>),
         <span class="dt">mortality=</span><span class="kw">round</span>(mortality,<span class="dv">2</span>),<span class="dt">density=</span><span class="kw">round</span>(density,<span class="dv">2</span>)) </code></pre></div>
<p>Look at the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_va <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>() <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">above_60</th>
<th align="right">life_exp</th>
<th align="right">fertility</th>
<th align="right">pop</th>
<th align="right">density</th>
<th align="right">mortality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">4.50</td>
<td align="right">26.85</td>
<td align="right">7.67</td>
<td align="right">77.52</td>
<td align="right">11.89</td>
<td align="right">439.56</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">10.13</td>
<td align="right">54.48</td>
<td align="right">5.80</td>
<td align="right">12.63</td>
<td align="right">43.94</td>
<td align="right">165.17</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">6.81</td>
<td align="right">42.77</td>
<td align="right">7.65</td>
<td align="right">88.72</td>
<td align="right">3.73</td>
<td align="right">292.13</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">4.94</td>
<td align="right">30.70</td>
<td align="right">6.93</td>
<td align="right">43.55</td>
<td align="right">3.49</td>
<td align="right">404.92</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">7.04</td>
<td align="right">61.61</td>
<td align="right">3.16</td>
<td align="right">171.50</td>
<td align="right">6.17</td>
<td align="right">93.53</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">12.46</td>
<td align="right">69.01</td>
<td align="right">3.07</td>
<td align="right">81.77</td>
<td align="right">1.06</td>
<td align="right">31.60</td>
</tr>
</tbody>
</table>
<p>Finally, write the data to a csv file. This file could be used in the future without have to use the long data processing steps.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write.csv</span>(gapminder_va,<span class="dt">file=</span><span class="st">&quot;data/Gapminder_final.csv&quot;</span>)</code></pre></div>
</div>
<div id="economic-data" class="section level3">
<h3><span class="header-section-number">2.3.9</span> Economic Data</h3>
<p>One last note is that we have not included an economic metric such as gross domestic product, GDP, per capita. The reason is that the data is sparse. On the gapminder website the data starts in 1960 and ends in 2011; in addition many countries are missing data. On the World Bank site, the data is more complete but still has many missing values and goes from 1960 to 2016. The data in the <strong>gapminder</strong> package in <code>R</code> has data for each country but only in five year increments and ends in 2007. if we want to include GDP data we would have to make the choice of limiting the number of years, interpolating, and/or removing more countries. It would be too much to extrapolate from 2007 to 2015, so a possible solution is to merge the World Bank data with the data from the <strong>gapminder</strong> package. However, they are inflation adjusted on different scales so a correction would have to be made. The World Bank data was in current US dollars while the <strong>gapminder</strong> package used something earlier, maybe 2000?</p>
<p>Here is some code to investigate how to incorporate GDP, but we will not complete it for our work. It is only a start to give an idea of the work involved.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_gdp_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/World Bank GDP.xlsx&quot;</span>,<span class="dt">skip=</span><span class="dv">4</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_gdp&lt;-gapminder_gdp_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,gdpPercap,<span class="op">-</span>(<span class="st">&quot;Country Name&quot;</span><span class="op">:</span><span class="st">&quot;Indicator Code&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>(<span class="st">`</span><span class="dt">Country Code</span><span class="st">`</span><span class="op">:</span><span class="st">`</span><span class="dt">Indicator Code</span><span class="st">`</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Country Name&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) </code></pre></div>
<p>There is a problem with the names of the countries again.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gdp_countries&lt;-<span class="kw">unique</span>(gapminder_gdp<span class="op">$</span>country)
countries[<span class="op">!</span>countries <span class="op">%in%</span><span class="st"> </span>gdp_countries]</code></pre></div>
<pre><code>## [1] &quot;Egypt&quot;            &quot;Gambia&quot;           &quot;Hong Kong, China&quot;
## [4] &quot;Iran&quot;             &quot;Korea, Dem. Rep.&quot; &quot;Reunion&quot;         
## [7] &quot;Syria&quot;            &quot;Taiwan&quot;           &quot;Venezuela&quot;</code></pre>
<p>Determine which countries are in the new data set and then correct the names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind&lt;-<span class="kw">vector</span>()
<span class="cf">for</span> (country <span class="cf">in</span> final_countries[<span class="op">!</span>final_countries <span class="op">%in%</span><span class="st"> </span>gdp_countries]){
  ind&lt;-<span class="kw">c</span>(ind,<span class="kw">grep</span>(<span class="kw">substr</span>(country,<span class="dv">1</span>,<span class="dv">6</span>),gdp_countries))
}
gdp_countries[ind]</code></pre></div>
<pre><code>## [1] &quot;Egypt, Arab Rep.&quot;          &quot;Gambia, The&quot;              
## [3] &quot;Iran, Islamic Rep.&quot;        &quot;Korea, Rep.&quot;              
## [5] &quot;Korea, Dem. People’s Rep.&quot; &quot;Syrian Arab Republic&quot;     
## [7] &quot;Venezuela, RB&quot;</code></pre>
<p>Fix the names. We know <em>Korea, Rep.</em> is correct, let’s remove it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind&lt;-ind[<span class="op">-</span><span class="dv">4</span>]</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Two vectors of names to run a loop over</span>
old_names&lt;-gdp_countries[ind]
new_names&lt;-final_countries[<span class="op">!</span>final_countries <span class="op">%in%</span><span class="st"> </span>gdp_countries]
<span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(new_names)){
gapminder_gdp<span class="op">$</span>country&lt;-<span class="kw">gsub</span>(old_names[i],new_names[i],gapminder_gdp<span class="op">$</span>country)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_gdp&lt;-gapminder_gdp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>final_countries,year<span class="op">&gt;=</span><span class="dv">1992</span>,year<span class="op">&lt;</span><span class="dv">2017</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(country,year)</code></pre></div>
<p>Add continents to the data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_gdp &lt;-<span class="st"> </span>gapminder_gdp <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,gdpPercap) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(year,country)</code></pre></div>
<p>Now get the data from the <strong>gapminder</strong> package and compare the years to determine how to adjust.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(gapminder_gdp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> </span><span class="dv">2007</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(gdpPercap)<span class="op">/</span>
gapminder <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> </span><span class="dv">2007</span>,country <span class="op">%in%</span><span class="st"> </span>final_countries) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(gdpPercap) <span class="op">-</span>
(gapminder_gdp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> </span><span class="dv">2002</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(gdpPercap)<span class="op">/</span>
gapminder <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> </span><span class="dv">2002</span>,country <span class="op">%in%</span><span class="st"> </span>final_countries) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(gdpPercap)))</code></pre></div>
<pre><code>##   gdpPercap
## 1 0.1210036
## 2 0.2911512
## 3 0.2968434
## 4 0.3436639
## 5 0.2697395
## 6 0.5360116</code></pre>
<p>The adjustment is not consistent so we may be lacking some understanding of how inflation adjustment is being done. Stop the process here but if you wanted to continue, you would adjust the data from the World Bank to be consistent with the <strong>gapminder</strong> data and then use interpolation similar to what was done with percentage of population above 60.</p>
<p>Clean our work space.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(gapminder_gdp_temp)
<span class="kw">rm</span>(gapminder_gdp)
<span class="kw">rm</span>(new_names)
<span class="kw">rm</span>(old_names)</code></pre></div>
</div>
<div id="summary-of-data-collection" class="section level3">
<h3><span class="header-section-number">2.3.10</span> Summary of Data Collection</h3>
<p>To recap the data collection process, we will explain each variable. There are 138 countries on 5 continents for the years 1950 through and including 2015. Table <a href="DataCol2.html#tab:final-tab">2.6</a> gives the first six rows of the data.</p>
<table>
<caption><span id="tab:final-tab">Table 2.6: </span>The First Rows of our Final Data Set</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">continent</th>
<th align="right">year</th>
<th align="right">above_60</th>
<th align="right">life_exp</th>
<th align="right">fertility</th>
<th align="right">pop</th>
<th align="right">density</th>
<th align="right">mortality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="left">Asia</td>
<td align="right">1950</td>
<td align="right">4.50</td>
<td align="right">26.85</td>
<td align="right">7.67</td>
<td align="right">77.52</td>
<td align="right">11.89</td>
<td align="right">439.56</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">Europe</td>
<td align="right">1950</td>
<td align="right">10.13</td>
<td align="right">54.48</td>
<td align="right">5.80</td>
<td align="right">12.63</td>
<td align="right">43.94</td>
<td align="right">165.17</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">6.81</td>
<td align="right">42.77</td>
<td align="right">7.65</td>
<td align="right">88.72</td>
<td align="right">3.73</td>
<td align="right">292.13</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="left">Africa</td>
<td align="right">1950</td>
<td align="right">4.94</td>
<td align="right">30.70</td>
<td align="right">6.93</td>
<td align="right">43.55</td>
<td align="right">3.49</td>
<td align="right">404.92</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="left">Americas</td>
<td align="right">1950</td>
<td align="right">7.04</td>
<td align="right">61.61</td>
<td align="right">3.16</td>
<td align="right">171.50</td>
<td align="right">6.17</td>
<td align="right">93.53</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="left">Oceania</td>
<td align="right">1950</td>
<td align="right">12.46</td>
<td align="right">69.01</td>
<td align="right">3.07</td>
<td align="right">81.77</td>
<td align="right">1.06</td>
<td align="right">31.60</td>
</tr>
</tbody>
</table>
<p>Table <a href="DataCol2.html#tab:data-desc">2.7</a> summarizes the variables in our final data set.</p>
<table>
<caption><span id="tab:data-desc">Table 2.7: </span>Description of Variables</caption>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">above_60</td>
<td align="left">The percentage of the total population in a country that is above 60 years of age</td>
</tr>
<tr class="even">
<td align="left">life_exp</td>
<td align="left">The average number of years a newborn child would live if current mortality patterns were to stay the same</td>
</tr>
<tr class="odd">
<td align="left">fertility</td>
<td align="left">The number of children that would be born to each woman with prevailing age-specific fertility rates</td>
</tr>
<tr class="even">
<td align="left">pop</td>
<td align="left">The population of the country (100,000 people)</td>
</tr>
<tr class="odd">
<td align="left">density</td>
<td align="left">The population of the country divided by the area of the country</td>
</tr>
<tr class="even">
<td align="left">mortality</td>
<td align="left">The probability that a child born in a specific year will die before reaching the age of five if subject to current age-specific mortality rates. Expressed as a rate per 1,000 live births</td>
</tr>
</tbody>
</table>
<p>In the next section, we will explore the process of visualizing the data.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Intro2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Viz2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/BawCOS/teaching-visual-analytics/edit/master/02-Exploratory-Visual-Analytics.Rmd",
"text": "Edit"
},
"download": ["VA-Notes.pdf", "VA-Notes.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
