<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lesson Modules for Teaching Visual Analytics</title>
  <meta name="description" content="Lessons on teaching visual analytics in a generic undergraduate classroom">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Lesson Modules for Teaching Visual Analytics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lessons on teaching visual analytics in a generic undergraduate classroom" />
  <meta name="github-repo" content="BawCOS/teaching-visual-analytics" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lesson Modules for Teaching Visual Analytics" />
  
  <meta name="twitter:description" content="Lessons on teaching visual analytics in a generic undergraduate classroom" />
  

<meta name="author" content="Bradley Warner">
<meta name="author" content="David Ebert">


<meta name="date" content="2018-03-21">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="Intro2.html">
<link rel="next" href="Chpt3.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.9/htmlwidgets.js"></script>
<script src="libs/datatables-binding-0.2/datatables.js"></script>
<link href="libs/dt-core-1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.12/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.12/js/jquery.dataTables.min.js"></script>
<link href="libs/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet" />
<script src="libs/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<script src="libs/jquery-ui-1.11.4/jquery.ui.touch-punch.min.js"></script>
<link href="libs/c3-0.4.11/c3.min.css" rel="stylesheet" />
<script src="libs/c3-0.4.11/c3.min.js"></script>
<script src="libs/d3-3.5.9/d3.min.js"></script>
<link href="libs/pivottable-2.11.0/pivot.min.css" rel="stylesheet" />
<script src="libs/pivottable-2.11.0/pivot.min.js"></script>
<script src="libs/pivottable_d3renderers-2.11.0/d3_renderers.min.js"></script>
<script src="libs/pivottable_c3renderers-2.11.0/c3_renderers.min.js"></script>
<script src="libs/polyfill-0.1/polyfill.min.js"></script>
<link href="libs/rpivotTable_style-0.1/rpivotTable.css" rel="stylesheet" />
<script src="libs/rpivotTable-binding-0.2.0/rpivotTable.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.2/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.2/js/bootstrap.min.js"></script>
<link href="libs/ionrangeslider-2.1.2/css/ion.rangeSlider.css" rel="stylesheet" />
<link href="libs/ionrangeslider-2.1.2/css/ion.rangeSlider.skinShiny.css" rel="stylesheet" />
<script src="libs/ionrangeslider-2.1.2/js/ion.rangeSlider.min.js"></script>
<script src="libs/strftime-0.9.2/strftime-min.js"></script>
<link href="libs/selectize-0.11.2/css/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.11.2/js/selectize.min.js"></script>
<link href="libs/d3scatter-0.0.0/d3scatter.css" rel="stylesheet" />
<script src="libs/d3scatter-0.0.0/d3scatter.js"></script>
<script src="libs/d3scatter-binding-0.1.0/d3scatter.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Lesson Notes for Visual Analytics</a></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="who-is-this-book-for.html"><a href="who-is-this-book-for.html"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="book-structure-and-how-to-use-it.html"><a href="book-structure-and-how-to-use-it.html"><i class="fa fa-check"></i><b>0.2</b> Book Structure and How to Use It</a></li>
<li class="chapter" data-level="0.3" data-path="prerequisites.html"><a href="prerequisites.html"><i class="fa fa-check"></i><b>0.3</b> Prerequisites</a></li>
<li class="chapter" data-level="0.4" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i><b>0.4</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="Chpt1.html"><a href="Chpt1.html"><i class="fa fa-check"></i><b>1</b> Introducing Visual Analytics - Emphasis on Analytic Reasoning</a><ul>
<li class="chapter" data-level="1.1" data-path="lesson-preparation.html"><a href="lesson-preparation.html"><i class="fa fa-check"></i><b>1.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="1.1.1" data-path="lesson-preparation.html"><a href="lesson-preparation.html#objectives"><i class="fa fa-check"></i><b>1.1.1</b> Objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="lesson-preparation.html"><a href="lesson-preparation.html#preparation"><i class="fa fa-check"></i><b>1.1.2</b> Preparation</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="Intro1.html"><a href="Intro1.html"><i class="fa fa-check"></i><b>1.2</b> Lesson Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="AR1.html"><a href="AR1.html"><i class="fa fa-check"></i><b>1.3</b> Analytic Reasoning</a><ul>
<li class="chapter" data-level="1.3.1" data-path="AR1.html"><a href="AR1.html#analytic-reasoing-explained"><i class="fa fa-check"></i><b>1.3.1</b> Analytic Reasoing Explained</a></li>
<li class="chapter" data-level="1.3.2" data-path="AR1.html"><a href="AR1.html#example"><i class="fa fa-check"></i><b>1.3.2</b> Example</a></li>
<li class="chapter" data-level="1.3.3" data-path="AR1.html"><a href="AR1.html#second-example"><i class="fa fa-check"></i><b>1.3.3</b> Second Example</a></li>
<li class="chapter" data-level="1.3.4" data-path="AR1.html"><a href="AR1.html#other-problem-ideas"><i class="fa fa-check"></i><b>1.3.4</b> Other problem ideas:</a></li>
<li class="chapter" data-level="1.3.5" data-path="AR1.html"><a href="AR1.html#using-analytic-reasoning."><i class="fa fa-check"></i><b>1.3.5</b> Using Analytic Reasoning.</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="Viz1.html"><a href="Viz1.html"><i class="fa fa-check"></i><b>1.4</b> Visualizing data (Re-representation)</a><ul>
<li class="chapter" data-level="1.4.1" data-path="Viz1.html"><a href="Viz1.html#background-on-visualizing-data"><i class="fa fa-check"></i><b>1.4.1</b> Background on Visualizing Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="Viz1.html"><a href="Viz1.html#using-problem"><i class="fa fa-check"></i><b>1.4.2</b> Using Problem</a></li>
<li class="chapter" data-level="1.4.3" data-path="Viz1.html"><a href="Viz1.html#discussion-ideas-4"><i class="fa fa-check"></i><b>1.4.3</b> Discussion ideas</a></li>
<li class="chapter" data-level="1.4.4" data-path="Viz1.html"><a href="Viz1.html#visualization"><i class="fa fa-check"></i><b>1.4.4</b> Visualization</a></li>
<li class="chapter" data-level="1.4.5" data-path="Viz1.html"><a href="Viz1.html#vectors-for-visualization"><i class="fa fa-check"></i><b>1.4.5</b> Vectors for Visualization</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="Inert1.html"><a href="Inert1.html"><i class="fa fa-check"></i><b>1.5</b> Interaction</a><ul>
<li class="chapter" data-level="1.5.1" data-path="Inert1.html"><a href="Inert1.html#background-information-on-interaction"><i class="fa fa-check"></i><b>1.5.1</b> Background Information on Interaction</a></li>
<li class="chapter" data-level="1.5.2" data-path="Inert1.html"><a href="Inert1.html#our-problem"><i class="fa fa-check"></i><b>1.5.2</b> Our Problem</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="final-product.html"><a href="final-product.html"><i class="fa fa-check"></i><b>1.6</b> Final Product</a><ul>
<li class="chapter" data-level="1.6.1" data-path="final-product.html"><a href="final-product.html#discussion-ideas-12"><i class="fa fa-check"></i><b>1.6.1</b> Discussion Ideas</a></li>
<li class="chapter" data-level="1.6.2" data-path="final-product.html"><a href="final-product.html#first-knowledge-product"><i class="fa fa-check"></i><b>1.6.2</b> First Knowledge Product</a></li>
<li class="chapter" data-level="1.6.3" data-path="final-product.html"><a href="final-product.html#discussion-ideas-13"><i class="fa fa-check"></i><b>1.6.3</b> Discussion Ideas</a></li>
<li class="chapter" data-level="1.6.4" data-path="final-product.html"><a href="final-product.html#second-knowledge-product"><i class="fa fa-check"></i><b>1.6.4</b> Second Knowledge Product</a></li>
<li class="chapter" data-level="1.6.5" data-path="final-product.html"><a href="final-product.html#web-resources"><i class="fa fa-check"></i><b>1.6.5</b> Web Resources</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="Conc1.html"><a href="Conc1.html"><i class="fa fa-check"></i><b>1.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Chpt2.html"><a href="Chpt2.html"><i class="fa fa-check"></i><b>2</b> Exploratory Visual Analytics</a><ul>
<li class="chapter" data-level="2.1" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html"><i class="fa fa-check"></i><b>2.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="2.1.1" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html#objectives-1"><i class="fa fa-check"></i><b>2.1.1</b> Objectives:</a></li>
<li class="chapter" data-level="2.1.2" data-path="lesson-preparation-1.html"><a href="lesson-preparation-1.html#preparation-1"><i class="fa fa-check"></i><b>2.1.2</b> Preparation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="Intro2.html"><a href="Intro2.html"><i class="fa fa-check"></i><b>2.2</b> Lesson Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="data-collection.html"><a href="data-collection.html"><i class="fa fa-check"></i><b>2.3</b> Data Collection</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Chpt3.html"><a href="Chpt3.html"><i class="fa fa-check"></i><b>3</b> Data Visualiztions</a></li>
<li class="chapter" data-level="4" data-path="Chpt4.html"><a href="Chpt4.html"><i class="fa fa-check"></i><b>4</b> Interactions</a><ul>
<li class="chapter" data-level="4.1" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html"><i class="fa fa-check"></i><b>4.1</b> Lesson Preparation</a><ul>
<li class="chapter" data-level="4.1.1" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html#objectives-2"><i class="fa fa-check"></i><b>4.1.1</b> Objectives:</a></li>
<li class="chapter" data-level="4.1.2" data-path="lesson-preparation-2.html"><a href="lesson-preparation-2.html#preparation-2"><i class="fa fa-check"></i><b>4.1.2</b> Preparation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="case-study.html"><a href="case-study.html"><i class="fa fa-check"></i><b>5</b> Case Study</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="AppA.html"><a href="AppA.html"><i class="fa fa-check"></i><b>A</b> Lesson Handouts</a></li>
<li class="chapter" data-level="B" data-path="AppB.html"><a href="AppB.html"><i class="fa fa-check"></i><b>B</b> Project</a><ul>
<li class="chapter" data-level="B.0.1" data-path="AppB.html"><a href="AppB.html#introduction"><i class="fa fa-check"></i><b>B.0.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bawcos.github.io/teaching-visual-analytics/" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lesson Modules for Teaching Visual Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-collection" class="section level2">
<h2><span class="header-section-number">2.3</span> Data Collection</h2>
<p>The data for this lesson comes from the <a href="https://www.gapminder.org/data/">Gapminder</a> website. Again, you could just start with the <strong>tools</strong> application on the website instead of using the R code here. This section will be long but remember that data wrangling can take up to 80% of the time in a project.</p>
<p>First we will load two pacages we need. The data is downloaded in a Excel spreadsheet; we will use the package <strong>readxl</strong> to read it. In addition, R has a package called <strong>gapminder</strong> which is a subset of the data from the Gapminder website. We will use it to get country names to reduce the size of our data and exclude countries with a large amount of missing data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readxl)
<span class="kw">library</span>(gapminder)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(tidyverse)</code></pre></div>
<p>The data has been downloaded and is in the <strong>data</strong> folder on the GitHub site for this book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator gapminder population.xlsx&quot;</span>)
gapminder_population_temp</code></pre></div>
<pre><code>## # A tibble: 275 x 82
##    `Total~ `1800.~ `1810.~ `1820.~ `1830.~ `1840.~ `1850.~ `1860.~ `1870.~
##    &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 Abkhaz~      NA      NA      NA      NA      NA      NA      NA      NA
##  2 Afghan~ 3280000 3280000 3323519 3448982 3625022 3810047 3973968 4169690
##  3 Akroti~      NA      NA      NA      NA      NA      NA      NA      NA
##  4 Albania  410445  423591  438671  457234  478227  506889  552800  610036
##  5 Algeria 2503218 2595056 2713079 2880355 3082721 3299305 3536468 3811028
##  6 Americ~    8170    8156    8142    8128    8114    7958    7564    7057
##  7 Andorra    2654    2654    2700    2835    3026    3230    3436    3654
##  8 Angola  1567028 1567028 1597530 1686390 1813100 1949329 2110747 2285417
##  9 Anguil~    2025    2025    2064    2177    2338    2511    2693    2888
## 10 Antigu~   37000   37000   37000   37000   37000   37000   36532   35546
## # ... with 265 more rows, and 73 more variables: `1880.0` &lt;dbl&gt;, `1890.0`
## #   &lt;dbl&gt;, `1900.0` &lt;dbl&gt;, `1910.0` &lt;dbl&gt;, `1920.0` &lt;dbl&gt;, `1930.0` &lt;dbl&gt;,
## #   `1940.0` &lt;dbl&gt;, `1950.0` &lt;dbl&gt;, `1951.0` &lt;dbl&gt;, `1952.0` &lt;dbl&gt;,
## #   `1953.0` &lt;dbl&gt;, `1954.0` &lt;dbl&gt;, `1955.0` &lt;dbl&gt;, `1956.0` &lt;dbl&gt;,
## #   `1957.0` &lt;dbl&gt;, `1958.0` &lt;dbl&gt;, `1959.0` &lt;dbl&gt;, `1960.0` &lt;dbl&gt;,
## #   `1961.0` &lt;dbl&gt;, `1962.0` &lt;dbl&gt;, `1963.0` &lt;dbl&gt;, `1964.0` &lt;dbl&gt;,
## #   `1965.0` &lt;dbl&gt;, `1966.0` &lt;dbl&gt;, `1967.0` &lt;dbl&gt;, `1968.0` &lt;dbl&gt;,
## #   `1969.0` &lt;dbl&gt;, `1970.0` &lt;dbl&gt;, `1971.0` &lt;dbl&gt;, `1972.0` &lt;dbl&gt;,
## #   `1973.0` &lt;dbl&gt;, `1974.0` &lt;dbl&gt;, `1975.0` &lt;dbl&gt;, `1976.0` &lt;dbl&gt;,
## #   `1977.0` &lt;dbl&gt;, `1978.0` &lt;dbl&gt;, `1979.0` &lt;dbl&gt;, `1980.0` &lt;dbl&gt;,
## #   `1981.0` &lt;dbl&gt;, `1982.0` &lt;dbl&gt;, `1983.0` &lt;dbl&gt;, `1984.0` &lt;dbl&gt;,
## #   `1985.0` &lt;dbl&gt;, `1986.0` &lt;dbl&gt;, `1987.0` &lt;dbl&gt;, `1988.0` &lt;dbl&gt;,
## #   `1989.0` &lt;dbl&gt;, `1990.0` &lt;dbl&gt;, `1991.0` &lt;dbl&gt;, `1992.0` &lt;dbl&gt;,
## #   `1993.0` &lt;dbl&gt;, `1994.0` &lt;dbl&gt;, `1995.0` &lt;dbl&gt;, `1996.0` &lt;dbl&gt;,
## #   `1997.0` &lt;dbl&gt;, `1998.0` &lt;dbl&gt;, `1999.0` &lt;dbl&gt;, `2000.0` &lt;dbl&gt;,
## #   `2001.0` &lt;dbl&gt;, `2002.0` &lt;dbl&gt;, `2003.0` &lt;dbl&gt;, `2004.0` &lt;dbl&gt;,
## #   `2005.0` &lt;dbl&gt;, `2006.0` &lt;dbl&gt;, `2007.0` &lt;dbl&gt;, `2008.0` &lt;dbl&gt;,
## #   `2009.0` &lt;dbl&gt;, `2010.0` &lt;dbl&gt;, `2011.0` &lt;dbl&gt;, `2012.0` &lt;dbl&gt;,
## #   `2013.0` &lt;dbl&gt;, `2014.0` &lt;dbl&gt;, `2015.0` &lt;dbl&gt;</code></pre>
<p>From the <strong>gapminder</strong> package, we will get the subset of countries where the data is most complete.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries&lt;-<span class="kw">levels</span>(gapminder<span class="op">$</span>country)</code></pre></div>
<p>Finally, we will wrangle the data into the final form needed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,pop,<span class="op">-</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year),<span class="dt">pop=</span><span class="kw">as.integer</span>(pop)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)
gapminder_population</code></pre></div>
<pre><code>## # A tibble: 9,174 x 3
##    country      year      pop
##    &lt;chr&gt;       &lt;int&gt;    &lt;int&gt;
##  1 Afghanistan  1950  7752118
##  2 Albania      1950  1263171
##  3 Algeria      1950  8872247
##  4 Angola       1950  4354882
##  5 Argentina    1950 17150335
##  6 Australia    1950  8177344
##  7 Austria      1950  6936445
##  8 Bahrain      1950   115614
##  9 Bangladesh   1950 37894680
## 10 Belgium      1950  8628489
## # ... with 9,164 more rows</code></pre>
<p>Before proceeding. We will check the quality of the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(countries)</code></pre></div>
<pre><code>## [1] 142</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))</code></pre></div>
<pre><code>## [1] 139</code></pre>
<p>There are 142 countries in the <strong>gapminder</strong> data but only 139 in the data we collected. These names might be different from those from the imported data. We will check that first.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries[<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;Korea, Dem. Rep.&quot; &quot;Korea, Rep.&quot;      &quot;Yemen, Rep.&quot;</code></pre>
<p>We are missing the two Koreas and Yemen from our data.</p>
<p>We need the full list of countries, so we have to start over.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,pop,<span class="op">-</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year),<span class="dt">pop=</span><span class="kw">as.integer</span>(pop)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year<span class="op">&gt;=</span><span class="dv">1950</span>)
gapminder_population</code></pre></div>
<pre><code>## # A tibble: 18,150 x 3
##    country                year     pop
##    &lt;chr&gt;                 &lt;int&gt;   &lt;int&gt;
##  1 Abkhazia               1950      NA
##  2 Afghanistan            1950 7752118
##  3 Akrotiri and Dhekelia  1950   10661
##  4 Albania                1950 1263171
##  5 Algeria                1950 8872247
##  6 American Samoa         1950   18937
##  7 Andorra                1950    6197
##  8 Angola                 1950 4354882
##  9 Anguilla               1950    5121
## 10 Antigua and Barbuda    1950   46301
## # ... with 18,140 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Korea&quot;</span>,<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;North Korea&quot;           &quot;South Korea&quot;           &quot;United Korea (former)&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)[<span class="kw">grep</span>(<span class="st">&quot;Yemen&quot;</span>,<span class="kw">unique</span>(gapminder_population<span class="op">$</span>country))]</code></pre></div>
<pre><code>## [1] &quot;North Yemen (former)&quot; &quot;South Yemen (former)&quot; &quot;Yemen&quot;</code></pre>
<p>We now know the problem is that in the <strong>gapminder</strong> package we have the titles “Korea, Dem. Rep.”<br />
“Korea, Rep.”<br />
“Yemen, Rep.”</p>
<p>while in our data from the gapminder website we have the names “North Korea”<br />
“South Korea” “Yemen”</p>
<p>We will correct the names in the countries vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">which</span>(<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)))</code></pre></div>
<pre><code>## [1]  70  71 140</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">countries[<span class="dv">70</span>]=<span class="st">&quot;North Korea&quot;</span>
countries[<span class="dv">71</span>]=<span class="st">&quot;South Korea&quot;</span>
countries[<span class="dv">140</span>]=<span class="st">&quot;Yemen&quot;</span></code></pre></div>
<p>We will check our data again.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="op">!</span>(countries <span class="op">%in%</span><span class="st"> </span><span class="kw">unique</span>(gapminder_population<span class="op">$</span>country)))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population&lt;-gapminder_population_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,pop,<span class="op">-</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total population&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year),<span class="dt">pop=</span><span class="kw">as.integer</span>(pop)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)
gapminder_population</code></pre></div>
<pre><code>## # A tibble: 9,372 x 3
##    country      year      pop
##    &lt;chr&gt;       &lt;int&gt;    &lt;int&gt;
##  1 Afghanistan  1950  7752118
##  2 Albania      1950  1263171
##  3 Algeria      1950  8872247
##  4 Angola       1950  4354882
##  5 Argentina    1950 17150335
##  6 Australia    1950  8177344
##  7 Austria      1950  6936445
##  8 Bahrain      1950   115614
##  9 Bangladesh   1950 37894680
## 10 Belgium      1950  8628489
## # ... with 9,362 more rows</code></pre>
<p>As a check, we will look for missing observations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),]</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   country  year   pop
##   &lt;chr&gt;   &lt;int&gt; &lt;int&gt;
## 1 Taiwan   2014    NA
## 2 Taiwan   2015    NA</code></pre>
<p>We are missing the last two years of data for Taiwan. We could drop Taiwan or get another estimate of the population from the web. Using the website <a href="http://www.worldometers.info/world-population/taiwan-population/" class="uri">http://www.worldometers.info/world-population/taiwan-population/</a> we see that for the last four years the population has grown by about 70000 each year. So we will estimate the population for 2014 and 2015 by adding 70000 to the population in 2013 for each year..</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),][<span class="dv">1</span>,<span class="dv">3</span>]=<span class="dv">23151000</span> <span class="op">+</span><span class="st"> </span><span class="dv">70000</span>
gapminder_population[<span class="kw">is.na</span>(gapminder_population<span class="op">$</span>pop),][<span class="dv">1</span>,<span class="dv">3</span>]=<span class="dv">23151000</span> <span class="op">+</span><span class="st"> </span><span class="dv">140000</span></code></pre></div>
<p>Now we need to add the continents to the dataframe.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dict&lt;-gapminder <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(continent) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="kw">as.character</span>(country))</code></pre></div>
<p>We still have the problem with the three countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dict<span class="op">$</span>country[<span class="kw">is.na</span>(<span class="kw">match</span>(dict<span class="op">$</span>country,countries))]</code></pre></div>
<pre><code>## [1] &quot;Korea, Dem. Rep.&quot; &quot;Korea, Rep.&quot;      &quot;Yemen, Rep.&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dict<span class="op">$</span>country[<span class="kw">is.na</span>(<span class="kw">match</span>(dict<span class="op">$</span>country,countries))]=<span class="kw">c</span>(<span class="st">&quot;North Korea&quot;</span>,<span class="st">&quot;South Korea&quot;</span>,<span class="st">&quot;Yemen&quot;</span>)</code></pre></div>
<p>Now we will add continent to the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_population &lt;-<span class="st"> </span>gapminder_population <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,pop)
gapminder_population</code></pre></div>
<pre><code>## # A tibble: 9,372 x 4
##    country     continent  year      pop
##    &lt;chr&gt;       &lt;fctr&gt;    &lt;int&gt;    &lt;dbl&gt;
##  1 Afghanistan Asia       1950  7752118
##  2 Albania     Europe     1950  1263171
##  3 Algeria     Africa     1950  8872247
##  4 Angola      Africa     1950  4354882
##  5 Argentina   Americas   1950 17150335
##  6 Australia   Oceania    1950  8177344
##  7 Austria     Europe     1950  6936445
##  8 Bahrain     Asia       1950   115614
##  9 Bangladesh  Asia       1950 37894680
## 10 Belgium     Europe     1950  8628489
## # ... with 9,362 more rows</code></pre>
<p>Clean up by removing temporary objects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(gapminder_population_temp)</code></pre></div>
<p>Next we bring in life expectancy data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator life_expectancy_at_birth.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp&lt;-gapminder_lifeexp_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,life_exp,<span class="op">-</span><span class="st">&quot;Life expectancy&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Life expectancy&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_lifeexp_temp)
gapminder_lifeexp</code></pre></div>
<pre><code>## # A tibble: 9,514 x 3
##    country      year life_exp
##    &lt;chr&gt;       &lt;int&gt;    &lt;dbl&gt;
##  1 Afghanistan  1950     26.8
##  2 Albania      1950     54.5
##  3 Algeria      1950     42.8
##  4 Angola       1950     30.7
##  5 Argentina    1950     61.6
##  6 Australia    1950     69.0
##  7 Austria      1950     64.9
##  8 Bahrain      1950     41.0
##  9 Bangladesh   1950     42.5
## 10 Belgium      1950     66.3
## # ... with 9,504 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_lifeexp &lt;-<span class="st"> </span>gapminder_lifeexp <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,life_exp)
gapminder_lifeexp</code></pre></div>
<pre><code>## # A tibble: 9,514 x 4
##    country     continent  year life_exp
##    &lt;chr&gt;       &lt;fctr&gt;    &lt;int&gt;    &lt;dbl&gt;
##  1 Afghanistan Asia       1950     26.8
##  2 Albania     Europe     1950     54.5
##  3 Algeria     Africa     1950     42.8
##  4 Angola      Africa     1950     30.7
##  5 Argentina   Americas   1950     61.6
##  6 Australia   Oceania    1950     69.0
##  7 Austria     Europe     1950     64.9
##  8 Bahrain     Asia       1950     41.0
##  9 Bangladesh  Asia       1950     42.5
## 10 Belgium     Europe     1950     66.3
## # ... with 9,504 more rows</code></pre>
<p>Next is fertility rates.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator undata total_fertility.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility&lt;-gapminder_fertility_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,fertility,<span class="op">-</span><span class="st">&quot;Total fertility rate&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total fertility rate&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_fertility_temp)
gapminder_fertility</code></pre></div>
<pre><code>## # A tibble: 9,372 x 3
##    country      year fertility
##    &lt;chr&gt;       &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan  1950      7.67
##  2 Albania      1950      5.80
##  3 Algeria      1950      7.65
##  4 Angola       1950      6.93
##  5 Argentina    1950      3.16
##  6 Australia    1950      3.07
##  7 Austria      1950      1.87
##  8 Bahrain      1950      7.03
##  9 Bangladesh   1950      6.23
## 10 Belgium      1950      2.30
## # ... with 9,362 more rows</code></pre>
<p>We need to check for missing values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_fertility<span class="op">$</span>fertility))</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility[<span class="kw">is.na</span>(gapminder_fertility<span class="op">$</span>fertility),]</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   country  year fertility
##   &lt;chr&gt;   &lt;int&gt;     &lt;dbl&gt;
## 1 Taiwan   2014        NA
## 2 Taiwan   2015        NA</code></pre>
<p>It is the country of Taiwan again that has missing values. I will estimate the fertility with average of the previous 5 years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp&lt;-<span class="kw">as.double</span>(gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Taiwan&quot;</span>,year<span class="op">&lt;</span><span class="dv">2014</span> <span class="op">&amp;</span><span class="st"> </span>year<span class="op">&gt;</span><span class="dv">2008</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">ave=</span><span class="kw">mean</span>(fertility)))
gapminder_fertility&lt;-gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">fertility=</span>temp))
<span class="kw">rm</span>(temp)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_fertility &lt;-<span class="st"> </span>gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,fertility)
gapminder_fertility</code></pre></div>
<pre><code>## # A tibble: 9,372 x 4
##    country     continent  year fertility
##    &lt;chr&gt;       &lt;fctr&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan Asia       1950      7.67
##  2 Albania     Europe     1950      5.80
##  3 Algeria     Africa     1950      7.65
##  4 Angola      Africa     1950      6.93
##  5 Argentina   Americas   1950      3.16
##  6 Australia   Oceania    1950      3.07
##  7 Austria     Europe     1950      1.87
##  8 Bahrain     Asia       1950      7.03
##  9 Bangladesh  Asia       1950      6.23
## 10 Belgium     Europe     1950      2.30
## # ... with 9,362 more rows</code></pre>
<p>Total above 60 (%)</p>
<p>Another thought may be that developed countries have an older population by percentage. We will next collect data on the percent of population above 60 years in age.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60_temp &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;data/indicator_total above 60 percen.xlsx&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60&lt;-gapminder_above60_temp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(year,above60,<span class="op">-</span><span class="st">&quot;Total above 60 (%)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country=</span><span class="st">&quot;Total above 60 (%)&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year=</span><span class="kw">as.integer</span>(year)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(country <span class="op">%in%</span><span class="st"> </span>countries,year<span class="op">&gt;=</span><span class="dv">1950</span>)
<span class="kw">rm</span>(gapminder_above60_temp)
gapminder_above60</code></pre></div>
<pre><code>## # A tibble: 2,835 x 3
##    country      year above60
##    &lt;chr&gt;       &lt;int&gt;   &lt;dbl&gt;
##  1 Afghanistan  1950    4.50
##  2 Albania      1950   10.1 
##  3 Algeria      1950    6.81
##  4 Angola       1950    4.94
##  5 Argentina    1950    7.04
##  6 Australia    1950   12.5 
##  7 Austria      1950   15.4 
##  8 Bahrain      1950    4.35
##  9 Bangladesh   1950    5.38
## 10 Belgium      1950   15.9 
## # ... with 2,825 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(gapminder_above60<span class="op">$</span>above60))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>No missing values.</p>
<p>But the data is only for every 5 years and has projections.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(gapminder_above60<span class="op">$</span>year)</code></pre></div>
<pre><code>##  [1] 1950 1955 1960 1965 1970 1975 1980 1985 1990 1995 2000 2005 2010 2015
## [15] 2020 2025 2030 2035 2040 2045 2050</code></pre>
<p>We will first remove the projections.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60 &lt;-<span class="st"> </span>gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(year <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2015</span>)</code></pre></div>
<p>Before we interpolate, let’s look at two countries to get an idea of the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p&lt;-gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span> <span class="op">|</span><span class="st"> </span>country<span class="op">==</span><span class="st">&quot;United States&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>year,<span class="dt">y=</span>above60,<span class="dt">color=</span>country))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()
p</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>We will use a spline to interpolate the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp1&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="kw">approx</span>(year,above60,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;Albania&quot;</span>)
temp2&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="kw">approx</span>(year,above60,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;United States&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp1&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;Albania&quot;</span>),<span class="kw">spline</span>(year,above60,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;Albania&quot;</span>)
temp2&lt;-<span class="kw">data.frame</span>(<span class="kw">with</span>(gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">filter</span>(country<span class="op">==</span><span class="st">&quot;United States&quot;</span>),<span class="kw">spline</span>(year,above60,<span class="dt">xout=</span><span class="kw">seq</span>(<span class="dv">1950</span>,<span class="dv">2015</span>)))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">country=</span><span class="st">&quot;United States&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp1,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>temp2,<span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y))</code></pre></div>
<p><img src="VA-Notes_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>Now we need to interpolate for every country and create our final data frame.</p>
<p>temp&lt;-gapminder_above60 %&gt;% filter(country==“Albania” | country == “United States”) tempa&lt;-data.frame(country=rep(c(“Albania”,“United States”),each=66),year=rep(seq(1950,2015),each=2)) tempa&lt;-as.tibble(tempa %&gt;% mutate(country=as.character(country))) tempa %&gt;% full_join(temp,by=“country”)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder_above60_temp &lt;-<span class="st"> </span>gapminder_above60 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(dict,<span class="dt">by=</span><span class="st">&quot;country&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(country,continent,year,above60)
gapminder_above60_temp</code></pre></div>
<pre><code>## # A tibble: 1,890 x 4
##    country     continent  year above60
##    &lt;chr&gt;       &lt;fctr&gt;    &lt;int&gt;   &lt;dbl&gt;
##  1 Afghanistan Asia       1950    4.50
##  2 Albania     Europe     1950   10.1 
##  3 Algeria     Africa     1950    6.81
##  4 Angola      Africa     1950    4.94
##  5 Argentina   Americas   1950    7.04
##  6 Australia   Oceania    1950   12.5 
##  7 Austria     Europe     1950   15.4 
##  8 Bahrain     Asia       1950    4.35
##  9 Bangladesh  Asia       1950    5.38
## 10 Belgium     Europe     1950   15.9 
## # ... with 1,880 more rows</code></pre>
<p>Data quality check</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_population<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_lifeexp<span class="op">$</span>continent)<span class="op">/</span><span class="dv">67</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gapminder_fertility<span class="op">$</span>continent)<span class="op">/</span><span class="dv">66</span></code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(dict<span class="op">$</span>continent)</code></pre></div>
<pre><code>## 
##   Africa Americas     Asia   Europe  Oceania 
##       52       25       33       30        2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (name <span class="cf">in</span> (dict <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(continent<span class="op">==</span><span class="st">&quot;Asia&quot;</span>))<span class="op">$</span>country){
  <span class="cf">if</span> (<span class="kw">length</span>((gapminder_fertility <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(country<span class="op">==</span>name))<span class="op">$</span>year)<span class="op">==</span><span class="dv">0</span>){<span class="kw">print</span>(name)}
  }</code></pre></div>

</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="Intro2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Chpt3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/BawCOS/teaching-visual-analytics/edit/master/02-Exploratory-Visual-Analytics.Rmd",
"text": "Edit"
},
"download": ["VA-Notes.pdf", "VA-Notes.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
